// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UgovorOZakupuService.Entities;

#nullable disable

namespace UgovorOZakupuService.Migrations
{
    [DbContext(typeof(UgovorOZakupuContext))]
    [Migration("20230217162415_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UgovorOZakupuService.Entities.UgovorOZakupuEntity", b =>
                {
                    b.Property<Guid>("UgovorOZakupuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumUgovora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeoParceleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DokumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OvlascenoLiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipGarancije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrajanjeUgovora")
                        .HasColumnType("int");

                    b.HasKey("UgovorOZakupuID");

                    b.ToTable("Ugovori");

                    b.HasData(
                        new
                        {
                            UgovorOZakupuID = new Guid("dc662e18-1bb0-4f43-bb36-b20eab32a292"),
                            DatumUgovora = new DateTime(2007, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeoParceleID = new Guid("006c5863-3eb4-4e65-afab-f3f653dec82a"),
                            DokumentID = new Guid("955b86da-6734-4972-93e5-9d46b0017bae"),
                            JavnoNadmetanjeID = new Guid("fa9c9d6b-e4ce-43b9-9bc9-04fc98872e19"),
                            KupacID = new Guid("035e91b3-55ab-4d36-b41b-95235a2efaa3"),
                            OvlascenoLiceID = new Guid("d3a26942-69f6-4f28-b5d2-05eba4b3ba1a"),
                            TipGarancije = "JEMSTVO",
                            TrajanjeUgovora = 8
                        },
                        new
                        {
                            UgovorOZakupuID = new Guid("1a41fbb4-ad86-4eec-be18-3ca94c1682cc"),
                            DatumUgovora = new DateTime(2007, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeoParceleID = new Guid("ba05b8cf-42dc-4d35-b5bc-5f309b7ca43e"),
                            DokumentID = new Guid("f9b78e65-f70d-4d3c-81a6-f0c687925d3d"),
                            JavnoNadmetanjeID = new Guid("c29c41d4-b729-41fe-a484-d04219fdb5a0"),
                            KupacID = new Guid("020c15d1-0928-4a1e-8fc1-45dcfa24c303"),
                            OvlascenoLiceID = new Guid("a332bcad-8049-4c73-a729-4fe6527b9ae7"),
                            TipGarancije = "BANKARSKAGARANCIJA",
                            TrajanjeUgovora = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
