// <auto-generated />
using System;
using DokumentiService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DokumentiService.Migrations
{
    [DbContext(typeof(DokumentContext))]
    [Migration("20230213235824_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DokumentiService.Entities.DokumentEntity", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatumDonosenja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EksterniDokumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterniDokumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sablon")
                        .HasColumnType("int");

                    b.Property<int>("StatusDokumenta")
                        .HasColumnType("int");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("DokumentiService.Entities.EksterniDokumentEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PutanjaDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EksterniDokumenti");

                    b.HasData(
                        new
                        {
                            ID = new Guid("475b61f1-dccd-404a-a657-43fb9ec729ce"),
                            PutanjaDokumenta = "Ovo je samo da vidimo sta ce da pise"
                        },
                        new
                        {
                            ID = new Guid("72922197-afd8-49ad-877b-6573b7d50714"),
                            PutanjaDokumenta = "Ovo je nesto nesto da vidimo sta ce da pise drugi deo brapoooo"
                        });
                });

            modelBuilder.Entity("DokumentiService.Entities.InterniDokumentEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PutanjaDokumenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("InterniDokumenti");

                    b.HasData(
                        new
                        {
                            ID = new Guid("858930f0-92ec-4975-b697-0c7afb2842de"),
                            PutanjaDokumenta = "Internal man"
                        },
                        new
                        {
                            ID = new Guid("9813acc5-35f5-4d3b-886c-42a6aaf162b9"),
                            PutanjaDokumenta = "Internal bratskciiii"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
