// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OvlascenoLiceService.Entities;

#nullable disable

namespace OvlascenoLiceService.Migrations
{
    [DbContext(typeof(OvlascenoLiceContext))]
    partial class OvlascenoLiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OvlascenoLiceService.Entities.FizickoLiceEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.ToTable("FizickaLica");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8cc7d67a-61ed-4795-ad0a-fa882eda0a2b"),
                            Ime = "Slavomirko",
                            JMBG = "4058851174218",
                            Prezime = "Slavimirkovic"
                        },
                        new
                        {
                            ID = new Guid("af948f2a-745b-45bc-abc1-1f4da1727af4"),
                            Ime = "Radomirko",
                            JMBG = "0786741214886",
                            Prezime = "Radimirkovic"
                        },
                        new
                        {
                            ID = new Guid("194e73cb-831e-40da-9ec8-0751c04a6b28"),
                            Ime = "Miladinko",
                            JMBG = "0925639560129",
                            Prezime = "Miladinkovic"
                        },
                        new
                        {
                            ID = new Guid("673eb87d-4a9f-4838-a542-3d4cef1b9495"),
                            Ime = "Milasinko",
                            JMBG = "9195579483423",
                            Prezime = "Milasnkovic"
                        },
                        new
                        {
                            ID = new Guid("4c504a89-419a-4f6f-8aae-31e0d3823e39"),
                            Ime = "Radasinko",
                            JMBG = "6675836696997",
                            Prezime = "Radasinkovic"
                        });
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.OvlascenoLiceEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FizickoLiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefon1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telefon2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("FizickoLiceID");

                    b.ToTable("OvlascenaLica");

                    b.HasData(
                        new
                        {
                            ID = new Guid("7b50cce0-050d-4833-bbc7-6b910bb6da89"),
                            AdresaID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            BrojRacuna = "343658891760636",
                            Email = "email1@net.org",
                            FizickoLiceID = new Guid("af948f2a-745b-45bc-abc1-1f4da1727af4"),
                            Telefon1 = "4211218533",
                            Telefon2 = "399461094"
                        },
                        new
                        {
                            ID = new Guid("1e24bea9-7df2-4d14-b224-c76fd77536dd"),
                            AdresaID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            BrojRacuna = "788066876873835",
                            Email = "email2@net.org",
                            FizickoLiceID = new Guid("af948f2a-745b-45bc-abc1-1f4da1727af4"),
                            Telefon1 = "377172253",
                            Telefon2 = "8048668952"
                        },
                        new
                        {
                            ID = new Guid("145c1e74-7eb5-4eaa-bf6a-bb84921c871e"),
                            AdresaID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            BrojRacuna = "801272932440773",
                            Email = "email3@net.org",
                            FizickoLiceID = new Guid("673eb87d-4a9f-4838-a542-3d4cef1b9495"),
                            Telefon1 = "4461663339",
                            Telefon2 = "4815540720"
                        },
                        new
                        {
                            ID = new Guid("904bd8b6-e268-4ca8-89fb-ef2750a74e19"),
                            AdresaID = new Guid("6f79d49c-1c14-49b7-94c3-19a81c7f97a0"),
                            BrojRacuna = "854823918379735",
                            Email = "email4@net.org",
                            FizickoLiceID = new Guid("673eb87d-4a9f-4838-a542-3d4cef1b9495"),
                            Telefon1 = "2481909941",
                            Telefon2 = ""
                        },
                        new
                        {
                            ID = new Guid("faea6877-c81e-4829-987e-ea68d5aea752"),
                            AdresaID = new Guid("6f79d49c-1c14-49b7-94c3-19a81c7f97a0"),
                            BrojRacuna = "252614852215342",
                            Email = "email5@net.org",
                            FizickoLiceID = new Guid("4c504a89-419a-4f6f-8aae-31e0d3823e39"),
                            Telefon1 = "5528150968",
                            Telefon2 = ""
                        });
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.OvlascenoLiceEntity", b =>
                {
                    b.HasOne("OvlascenoLiceService.Entities.FizickoLiceEntity", "FizickoLice")
                        .WithMany("Lica")
                        .HasForeignKey("FizickoLiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FizickoLice");
                });

            modelBuilder.Entity("OvlascenoLiceService.Entities.FizickoLiceEntity", b =>
                {
                    b.Navigation("Lica");
                });
#pragma warning restore 612, 618
        }
    }
}
