// <auto-generated />
using System;
using KorisniciService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KorisniciService.Migrations
{
    [DbContext(typeof(KorisnikContext))]
    [Migration("20230213180512_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KorisniciService.Entities.KorisnikEntity", b =>
                {
                    b.Property<Guid>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipKorisnika")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikID = new Guid("6e1a8ee2-c01d-484c-9da8-e50427fb298e"),
                            JavnoNadmetanjeID = new Guid("b49180d8-ff63-462d-8868-02c26ec0304c"),
                            Naziv = "Wynn Lagadu",
                            Sifra = "EjfkRqXrltLI",
                            TipKorisnika = "Tehnicki sekretar"
                        },
                        new
                        {
                            KorisnikID = new Guid("b0d223dd-c5f4-4bc3-ab9c-f83d8e374b1e"),
                            JavnoNadmetanjeID = new Guid("ce3c6508-b4d6-4b03-83c2-646baf4ed78b"),
                            Naziv = "Manuel Andriessen",
                            Sifra = "n4xxvQyQm",
                            TipKorisnika = "Operater Nadmetanja"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
