// <auto-generated />
using System;
using JavnoNadmetanjeService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JavnoNadmetanjeService.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    [Migration("20230218182901_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumNad")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeoParceleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IzlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicitacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Licitanti")
                        .HasColumnType("int");

                    b.Property<string>("Opstina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PeriodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("PocetnaCena")
                        .HasColumnType("int");

                    b.Property<int>("PrijavljeniKupci")
                        .HasColumnType("int");

                    b.Property<string>("StatusNadmetanja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipNadmetanja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VisinaCene")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VremeKraj")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VremePoc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("LicitacijaID");

                    b.ToTable("JavnoNadmetanje");

                    b.HasData(
                        new
                        {
                            ID = new Guid("73e131e6-50c4-4ce3-bcb6-b0f9c706f5cb"),
                            AdresaID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            BrojUcesnika = 95,
                            DatumNad = new DateTime(2022, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeoParceleID = new Guid("edf1f7ca-3b73-4cb8-8cfd-4bd615dd6ada"),
                            IzlicitiranaCena = 150000000,
                            Izuzeto = true,
                            Krug = 7,
                            KupacID = new Guid("ccc043c6-398c-485d-9840-092c0441ebe8"),
                            LicitacijaID = new Guid("1ecaca89-af8e-47d5-8a33-5f4ec2fcb04e"),
                            Licitanti = 32,
                            Opstina = "BIKOVO",
                            PeriodZakupa = 67,
                            PocetnaCena = 1000000,
                            PrijavljeniKupci = 52,
                            StatusNadmetanja = "PRVI_KRUG",
                            TipNadmetanja = "JAVNA_LICITACIJA",
                            VisinaCene = 92076,
                            VremeKraj = new DateTime(2022, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            VremePoc = new DateTime(2022, 8, 4, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("5d62b2c0-d13c-4f74-840f-ad96bf204d69"),
                            AdresaID = new Guid("6f79d49c-1c14-49b7-94c3-19a81c7f97a0"),
                            BrojUcesnika = 95,
                            DatumNad = new DateTime(2019, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeoParceleID = new Guid("3846acaf-3d0e-439a-bf27-85344934f2ca"),
                            IzlicitiranaCena = 34000000,
                            Izuzeto = false,
                            Krug = 5,
                            KupacID = new Guid("93d92981-a754-41d8-8d1f-b5462a9e0386"),
                            LicitacijaID = new Guid("01724de1-1281-4206-a9ee-a153ba559304"),
                            Licitanti = 39,
                            Opstina = "ZEDNIK",
                            PeriodZakupa = 28,
                            PocetnaCena = 400000,
                            PrijavljeniKupci = 52,
                            StatusNadmetanja = "DRUGI_KRUG_STARI",
                            TipNadmetanja = "OTVARANJE_ZATVORENIH_PONUDA",
                            VisinaCene = 45698,
                            VremeKraj = new DateTime(2019, 5, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VremePoc = new DateTime(2019, 5, 25, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("abec715b-03e0-4c9a-b97b-327f0af16823"),
                            AdresaID = new Guid("878100df-6973-4292-acb1-0c25b7ac2260"),
                            BrojUcesnika = 18,
                            DatumNad = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeoParceleID = new Guid("dacea418-fdcc-4289-8a94-df82a7056c18"),
                            IzlicitiranaCena = 4900000,
                            Izuzeto = true,
                            Krug = 3,
                            KupacID = new Guid("4d1c0702-aeb4-4a4f-bdb8-26e1cc53b2eb"),
                            LicitacijaID = new Guid("77eb8e4b-ede1-4825-8da2-72d14c2d7259"),
                            Licitanti = 48,
                            Opstina = "DONJI_GRAD",
                            PeriodZakupa = 55,
                            PocetnaCena = 45900,
                            PrijavljeniKupci = 71,
                            StatusNadmetanja = "DRUGI_KRUG_NOVI",
                            TipNadmetanja = "JAVNA_LICITACIJA",
                            VisinaCene = 55942,
                            VremeKraj = new DateTime(2023, 1, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePoc = new DateTime(2023, 1, 16, 7, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.LicitacijaEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatumLicitacije")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("KorakCene")
                        .HasColumnType("int");

                    b.Property<int>("OgrnMaxPovrs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Rok")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Licitacija");

                    b.HasData(
                        new
                        {
                            ID = new Guid("1ecaca89-af8e-47d5-8a33-5f4ec2fcb04e"),
                            DatumLicitacije = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorakCene = 15,
                            OgrnMaxPovrs = 13,
                            Rok = new DateTime(2022, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("01724de1-1281-4206-a9ee-a153ba559304"),
                            DatumLicitacije = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorakCene = 150,
                            OgrnMaxPovrs = 17,
                            Rok = new DateTime(2022, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("77eb8e4b-ede1-4825-8da2-72d14c2d7259"),
                            DatumLicitacije = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorakCene = 150,
                            OgrnMaxPovrs = 17,
                            Rok = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.HasOne("JavnoNadmetanjeService.Entities.LicitacijaEntity", "Licitacija")
                        .WithMany("JavnaNadmetanja")
                        .HasForeignKey("LicitacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licitacija");
                });

            modelBuilder.Entity("JavnoNadmetanjeService.Entities.LicitacijaEntity", b =>
                {
                    b.Navigation("JavnaNadmetanja");
                });
#pragma warning restore 612, 618
        }
    }
}
