// <auto-generated />
using System;
using KupacService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KupacService.Migrations
{
    [DbContext(typeof(KupacContext))]
    partial class KupacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KupacService.Entities.KupacEntity", b =>
                {
                    b.Property<Guid>("KupacID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BrojKupovina")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumPocetkaZabrane")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavrsetkaZabrane")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ImaZabranu")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OvlascenoLiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("KupacID");

                    b.ToTable("Kupci");

                    b.HasData(
                        new
                        {
                            KupacID = new Guid("32b7d397-b9d1-472d-bb40-541c68305098"),
                            BrojKupovina = 0,
                            DatumPocetkaZabrane = new DateTime(2003, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZavrsetkaZabrane = new DateTime(2008, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImaZabranu = false,
                            JavnoNadmetanjeID = new Guid("32b7d397-b9d1-472d-bb40-542c68305018"),
                            LiceID = new Guid("32b7d397-b9d1-472d-bb40-542c68306098"),
                            OvlascenoLiceID = new Guid("32b7d397-b9d1-472d-bb40-542c68305094"),
                            Prioritet = "stagodtobilo"
                        },
                        new
                        {
                            KupacID = new Guid("32c7d397-b9d1-472d-bb40-542c68305098"),
                            BrojKupovina = 50,
                            DatumPocetkaZabrane = new DateTime(2002, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumZavrsetkaZabrane = new DateTime(2007, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImaZabranu = false,
                            JavnoNadmetanjeID = new Guid("32b7d367-b9d1-472d-bb40-542c68305098"),
                            LiceID = new Guid("32b4d397-b9d1-472d-bb40-542c68305098"),
                            OvlascenoLiceID = new Guid("12b7d397-b9d1-472d-bb40-542c68305098"),
                            Prioritet = "stagodtobilo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
