// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UplataService.Entities;

#nullable disable

namespace UplataService.Migrations
{
    [DbContext(typeof(UplataContext))]
    [Migration("20230218183153_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UplataService.Entities.UplataEntity", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DatumUplate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Iznos")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PozivNaBroj")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SvrhaUplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Uplatilac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UplataID");

                    b.ToTable("Uplate");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("460f3547-d626-49d7-92c4-6f96ae3714e0"),
                            BrojRacuna = "005-417672-67",
                            DatumUplate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iznos = 45000,
                            JavnoNadmetanjeID = new Guid("abec715b-03e0-4c9a-b97b-327f0af16823"),
                            KupacID = new Guid("ccc043c6-398c-485d-9840-092c0441ebe8"),
                            PozivNaBroj = "73609",
                            SvrhaUplate = "Uplata na racun",
                            Uplatilac = "Pera Peric"
                        },
                        new
                        {
                            UplataID = new Guid("167ef647-33c2-466c-b777-5271365bffbd"),
                            BrojRacuna = "214-826330-03",
                            DatumUplate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iznos = 1550,
                            JavnoNadmetanjeID = new Guid("5d62b2c0-d13c-4f74-840f-ad96bf204d69"),
                            KupacID = new Guid("753d20f5-73a3-4e00-a3a2-e1c43d6b0777"),
                            PozivNaBroj = "18096",
                            SvrhaUplate = "Racun za Telenor",
                            Uplatilac = "Sima Simic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
