// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UplataService.Entities;

#nullable disable

namespace UplataService.Migrations
{
    [DbContext(typeof(UplataContext))]
    partial class UplataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UplataService.Entities.UplataEntity", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DatumUplate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Iznos")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PozivNaBroj")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SvrhaUplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Uplatilac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UplataID");

                    b.ToTable("Uplate");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("460f3547-d626-49d7-92c4-6f96ae3714e0"),
                            BrojRacuna = "005-417672-67",
                            DatumUplate = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iznos = 45000,
                            JavnoNadmetanjeID = new Guid("03b0680e-35b6-4449-9150-019b817d7cef"),
                            KupacID = new Guid("32b7d397-b9d1-472d-bb40-541c68305098"),
                            PozivNaBroj = "73609",
                            SvrhaUplate = "Uplata na racun",
                            Uplatilac = "Pera Peric"
                        },
                        new
                        {
                            UplataID = new Guid("167ef647-33c2-466c-b777-5271365bffbd"),
                            BrojRacuna = "214-826330-03",
                            DatumUplate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Iznos = 1550,
                            JavnoNadmetanjeID = new Guid("43d6bc15-a674-4552-abee-f3c3360db11e"),
                            KupacID = new Guid("32c7d397-b9d1-472d-bb40-542c68305098"),
                            PozivNaBroj = "18096",
                            SvrhaUplate = "Racun za Telenor",
                            Uplatilac = "Sima Simic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
