// <auto-generated />
using System;
using LiceService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiceService.Migrations
{
    [DbContext(typeof(LiceContext))]
    [Migration("20230214120433_LiceMigration")]
    partial class LiceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiceService.Entities.FizickoLiceEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.ToTable("FizickaLica");

                    b.HasData(
                        new
                        {
                            ID = new Guid("32b7d397-b9d1-472d-bb40-542c68305098"),
                            Ime = "Slavomir",
                            JMBG = "4058851174218",
                            Prezime = "Slavic"
                        },
                        new
                        {
                            ID = new Guid("3a054c77-1bf4-4853-8937-8e36502a6848"),
                            Ime = "Radomir",
                            JMBG = "0786741214886",
                            Prezime = "Radic"
                        });
                });

            modelBuilder.Entity("LiceService.Entities.KontaktOsobaEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Funkcija")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("KontaktOsobe");
                });

            modelBuilder.Entity("LiceService.Entities.LiceEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FizickoLiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OvlascenoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Tel1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tel2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Lica");

                    b.HasData(
                        new
                        {
                            ID = new Guid("334f5277-a71c-4be8-b5da-5c9148b228f7"),
                            BrojRacuna = "123134132",
                            Email = "email1@net.org",
                            FizickoLiceID = new Guid("3a054c77-1bf4-4853-8937-8e36502a6848"),
                            OvlascenoLice = true,
                            Tel1 = "4211218533",
                            Tel2 = "399461094"
                        },
                        new
                        {
                            ID = new Guid("92e0d8e9-b221-42a6-9bb8-a80974aee937"),
                            BrojRacuna = "132423425",
                            Email = "email2@net.org",
                            FizickoLiceID = new Guid("3a054c77-1bf4-4853-8937-8e36502a6848"),
                            OvlascenoLice = false,
                            Tel1 = "377172253",
                            Tel2 = "8048668952"
                        },
                        new
                        {
                            ID = new Guid("f127642e-4d73-42f1-979d-6a506aea9bdc"),
                            BrojRacuna = "123235243123",
                            Email = "email3@net.org",
                            FizickoLiceID = new Guid("32b7d397-b9d1-472d-bb40-542c68305098"),
                            OvlascenoLice = false,
                            Tel1 = "4461663339",
                            Tel2 = "4815540720"
                        });
                });

            modelBuilder.Entity("LiceService.Entities.PravnoLiceEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KontaktOsobaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaticniBroj")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.ToTable("PravnaLica");
                });
#pragma warning restore 612, 618
        }
    }
}
