// <auto-generated />
using System;
using KomisijaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomisijaService.Migrations
{
    [DbContext(typeof(KomisijaContext))]
    [Migration("20230217220705_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KomisijaService.Entities.KomisijaEntity", b =>
                {
                    b.Property<Guid>("KomisijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan1ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan2ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan3ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Clan4ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Clan5ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PredsednikID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KomisijaID");

                    b.ToTable("Komisije");

                    b.HasData(
                        new
                        {
                            KomisijaID = new Guid("bc3a0d53-1862-4fbc-bb4d-7892f4199e69"),
                            Clan1ID = new Guid("08f2f910-eb7a-4714-9ef5-0fd1a2d1e278"),
                            Clan2ID = new Guid("063fe8c0-8b16-4fd5-960b-b130310040b0"),
                            Clan3ID = new Guid("e5875a1b-e03f-4a46-b7c2-c6f09f696034"),
                            Clan4ID = new Guid("b9f30780-f2e6-4475-b66e-44c588a1a252"),
                            Clan5ID = new Guid("63a84cc9-0c15-4acd-b2ef-c3aa44a03f7e"),
                            PredsednikID = new Guid("c35086d8-62c0-4166-8457-463066c8c659")
                        },
                        new
                        {
                            KomisijaID = new Guid("9b49e647-2850-406f-9e97-6673dfeead19"),
                            Clan1ID = new Guid("11ab0865-2d07-4d36-8ed4-f0acb07125e2"),
                            Clan2ID = new Guid("beffaa0f-2933-46d3-b1bd-746e9cc4dd9e"),
                            Clan3ID = new Guid("b27d89c8-d41b-4357-bb59-65013d0ce874"),
                            Clan4ID = new Guid("fc3e799c-53e5-4f3d-b6f8-d4e53686b913"),
                            Clan5ID = new Guid("887414d4-c3d0-40f7-abdf-a24d41e4d6e5"),
                            PredsednikID = new Guid("dfbbec1a-0e37-49a1-bed0-47a5cbbb660f")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
