// <auto-generated />
using System;
using KomisijaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomisijaService.Migrations
{
    [DbContext(typeof(KomisijaContext))]
    [Migration("20230213171550_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KomisijaService.Entities.KomisijaEntity", b =>
                {
                    b.Property<Guid>("KomisijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan1ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan2ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan3ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan4ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Clan5ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PredsednikID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KomisijaID");

                    b.ToTable("Komisije");
                });
#pragma warning restore 612, 618
        }
    }
}
