// <auto-generated />
using System;
using AdresaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdresaService.Migrations
{
    [DbContext(typeof(AdresaContext))]
    [Migration("20230213224453_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdresaService.Entities.AdresaEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<string>("Drzava")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mesto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Adresa");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            Broj = 11,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Slavoja Perica"
                        },
                        new
                        {
                            ID = new Guid("6f79d49c-1c14-49b7-94c3-19a81c7f97a0"),
                            Broj = 23,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Dositejeva"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
