// <auto-generated />
using System;
using AdresaService.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdresaService.Migrations
{
    [DbContext(typeof(AdresaContext))]
    [Migration("20230218031824_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdresaService.Entities.AdresaEntity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Adresa");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3aa0344b-57b5-450a-b83a-18c4555be65c"),
                            Broj = 11,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Slavoja Perica"
                        },
                        new
                        {
                            ID = new Guid("6f79d49c-1c14-49b7-94c3-19a81c7f97a0"),
                            Broj = 23,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Dositejeva"
                        },
                        new
                        {
                            ID = new Guid("878100df-6973-4292-acb1-0c25b7ac2260"),
                            Broj = 7,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Jevrejska"
                        },
                        new
                        {
                            ID = new Guid("accad5a2-e5bc-4ff5-a5b7-fc38ab8a47fe"),
                            Broj = 22,
                            Drzava = "Srbija",
                            Mesto = "Novi Sad",
                            PostanskiBroj = 22000,
                            Ulica = "Mise Dimitrijevica"
                        },
                        new
                        {
                            ID = new Guid("cbc77973-6f66-47b5-8b00-bdd9a2ab3650"),
                            Broj = 16,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 101801,
                            Ulica = "Brace Kovac"
                        },
                        new
                        {
                            ID = new Guid("e27e0caf-7d2b-4857-99de-71b63b503ae0"),
                            Broj = 45,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 101801,
                            Ulica = "Cerska"
                        },
                        new
                        {
                            ID = new Guid("d84c6e01-ea38-4d2d-b6d3-ca8eb0766c1e"),
                            Broj = 48,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 116468,
                            Ulica = "Dalmatinska"
                        },
                        new
                        {
                            ID = new Guid("f94d04c3-0af9-4753-a40a-59ddd3b1fe2d"),
                            Broj = 24,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 114412,
                            Ulica = "Murmanska"
                        },
                        new
                        {
                            ID = new Guid("7fe60739-ee19-42cb-bb3c-4016f2214a47"),
                            Broj = 12,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 116468,
                            Ulica = "Stojana Protica"
                        },
                        new
                        {
                            ID = new Guid("febe5ad4-c954-4244-bdf5-54d351e36653"),
                            Broj = 32,
                            Drzava = "Srbija",
                            Mesto = "Beograd",
                            PostanskiBroj = 112810,
                            Ulica = "Varvarinska"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
