// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZalbaService.Entities;

#nullable disable

namespace ZalbaService.Migrations
{
    [DbContext(typeof(ZalbaContext))]
    [Migration("20230213185606_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZalbaService.Entities.ZalbaEntity", b =>
                {
                    b.Property<Guid>("ZalbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatumPodnosenja")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Obrazlozenje")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RadnjaZalbe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Razlog")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusZalbe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipZalbe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZalbaID");

                    b.ToTable("Zalbe");

                    b.HasData(
                        new
                        {
                            ZalbaID = new Guid("08635d18-5f72-4050-8e5e-c520562675b1"),
                            DatumPodnosenja = new DateTime(2022, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KupacID = new Guid("fb046e3b-a95c-4079-9898-9e16d653d9a3"),
                            Obrazlozenje = "Neko obrazlozenje",
                            RadnjaZalbe = "JN ide u drugi krug sa novim uslovima",
                            Razlog = "Neki razlog",
                            StatusZalbe = "Usvojena",
                            TipZalbe = "Zalba na tok javnog nadmetanaja"
                        },
                        new
                        {
                            ZalbaID = new Guid("9014d78d-7b9b-4f63-b674-d83ed1d5356a"),
                            DatumPodnosenja = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KupacID = new Guid("6f356c53-1dfb-48fa-93a1-18577d5db2b6"),
                            Obrazlozenje = "Neko drugo obrazlozenje",
                            RadnjaZalbe = "JN ide u drugi krug sa starim uslovima",
                            Razlog = "Neki drugi razlog",
                            StatusZalbe = "Otvorena",
                            TipZalbe = "Zalba na Odluku o davanju nakoriscenje"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
